# @package _global_
defaults:
  - _self_

# Model configuration
decoder: "FRCNNv2"
backbone_name: "default"
freeze_backbone: false

# Backbone
# backbone: "default"  # 'resnet50' or "SAM_large_images" or "SAM_base_images"
dilation: true
# num_feature_levels: 1
# finetune_only_class_linear: false
num_classes: 2

# # Learning rate and optimizer parameters
batches_per_epoch: 100
batch_size: 12
accumulate_grad_batches: 2

# Optimization
learning_rate: 1e-4
lr_backbone_names: ["backbone"]
lr_backbone: 1e-5
weight_decay: 1e-4

# Model parameters
frozen_weights: null


# # Transformer
# enc_layers: 6
# dec_layers: 6
# dim_feedforward: 1024
# hidden_dim: 256  # 256
# dropout: 0.0
# nheads: 8  # 8
# num_query_position: 100
# num_query_pattern: 3
# spatial_prior: learned
# attention_type: RCDA

# Segmentation
masks: false

# # Loss
# aux_loss: true

# # Matcher
# set_cost_class: 2
# set_cost_bbox: 5
# set_cost_giou: 2

# # Loss coefficients
# mask_loss_coef: 1
# dice_loss_coef: 1
# cls_loss_coef: 2
# bbox_loss_coef: 5
# giou_loss_coef: 2
# focal_alpha: 0.9  # To account for ~10 organoids compared to 300 predictions. Originally: 0.25

# Dataset parameters
device: cuda

strong_augmentation: strong

# Logging and checkpointing
project_name: "OrganoidDetection"
sub_name: "frcnn_v2_strong_aug"
log_dir: "logs/"
