defaults:
  - _self_

# Dataset paths
train_dirs: ["MultiOrg_train_normal", "MultiOrg_train_macros", "OrgaSegment_train", "Tellu_train", "OrgaQuant_train"]
val_dirs: ["MultiOrg_val_normal", "MultiOrg_val_macros", "OrgaSegment_val", "Tellu_val", "OrgaQuant_val"]
test_dirs: ["OrgaExtractor_all", "NewData_all", "OrganoID_test", "OrganoID_test_C", "OrganoID_test_ACC", "OrganoID_test_Lung", "OrganoID_test_mouse", "MultiOrg_test_normal", "MultiOrg_test_macros", "OrgaSegment_test", "Tellu_test", "OrgaQuant_test"]

# Model configuration
decoder: ""
backbone_name: "default"
freeze_backbone: false

# Debugging
trace_compute: false
memory_snapshot: false
cache_10_samples: false

# Training settings
run: 2024
seed: null
accumulate_grad_batches: 1
batch_size: 8
batches_per_epoch: 100
max_epochs: 1000
use_sampler: true
sampling_groups: ["n_objects"]
max_oversampling: 10.0
n_validation_samples: 40

gradient_clip_val: 0.1
strong_augmentation: normal

# Pretrained checkpoint:
checkpoint_path: null

# Learning rate and optimizer parameters
learning_rate: 1e-4
weight_decay: 1e-4
lr_drop: 800

# Logging and checkpointing
project_name: "OrganoidDetection"
sub_name: "default"
log_dir: "logs/"

